function [fid] = hdr2Nhdr_Tensor(hdr,mat,fn) 
% hdr an existing nrrd hdr with the same dimentions
% fn - the name of the file to be written (with no extension).
% mat - the data file
if ~isfield(hdr,'spaceorigin')
    hdr.spaceorigin = [-41.5,-41.5,-39];
end
fid = fopen([fn '.nhdr'], 'w');
[pathstr, fn_short, ext] = fileparts(fn);

fprintf(fid, ['NRRD0005\n' ...
                '# Complete NRRD file format specification at:\n' ...
                '# http://teem.sourceforge.net/nrrd/format.html\n' ...
                'type: float\n' ...
                'dimension: 4\n' ...
                'space: %s\n' ...
                'sizes: %d %d %d %d\n' ...
                'space directions: none (%g,%g,%g) (%g,%g,%g) (%g,%g,%g)\n' ...
                'centerings: ??? cell cell cell\n'...                
                'kinds: %s %s %s %s\n' ...
                'endian: little\n' ...
                'encoding: raw\n' ...
                'space units: "mm" "mm" "mm"\n' ...
                'space origin: (%g,%g,%g)\n' ...
                'measurement frame: (%g,%g,%g) (%g,%g,%g) (%g,%g,%g)\n'...
                'data file: %s.raw\n'], ...
          hdr.space, hdr.sizes(1:4), hdr.spacedirections_matrix(:), char(hdr.kinds(1)),char(hdr.kinds(2)),char(hdr.kinds(3)),char(hdr.kinds(4)), hdr.spaceorigin, hdr.measurementframe,fn_short...
       );

fclose(fid);

fid = fopen([fn '.raw'], 'w');
fwrite(fid, cast(mat,'single'), 'single');
fclose(fid);
 % system(['rm -f ' fn '.raw.gz && gzip ' fn '.raw']); % compress
